name = "EMMREML"
uuid = "17ab0c9e-3765-11ea-3752-0b6d3436b043"
authors = ["Uche Godfrey Okeke & Deniz Akdemir <urchgene@gmail.com>"]
version = "0.1.0"

[deps]
AltDistributions = "875e7ca2-ab9d-5828-93ae-a098eac53262"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PedigreeBase = "9e3bf72a-84c4-4798-98fd-c28eed5cded1"
PositiveFactorizations = "85a6dd25-e78a-55b7-8502-1745935b8125"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
