name = "EMMREML"
uuid = "17ab0c9e-3765-11ea-3752-0b6d3436b043"
authors = ["Uche Godfrey Okeke & Deniz Akdemir <urchgene@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PositiveFactorizations = "85a6dd25-e78a-55b7-8502-1745935b8125"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
